#!/bin/bash

# $1 - name
# $2 - distrelease
# $3 - mountpoint

name=${1}
distrelease=${2}
mnt=${3}

case ${distrelease} in
    ubuntu*|debian*)
        echo "Setting hostname..."
        echo ${name} > ${mnt}/etc/hostname
        ;;
    fedora*|centos*|rhel*)
        echo "Setting hostname..."
        if [ -e ${mnt}/etc/sysconfig/network ]; then
            sed -i ${mnt}/etc/sysconfig/network -e "s/HOSTNAME=.*/HOSTNAME=${name}/"
        fi
        ;;
    *)
        echo "Skipping hostname.  Unknown distrelease"
        ;;
esac
