#!/bin/bash

# $1 - name
# $2 - distrelease
# $3 - mountpoint

name=${1}
distrelease=${2}
mnt=${3}

case ${distrelease} in
    ubuntu*|debian*)
	cat > ${mnt}/etc/network/interfaces <<EOF
auto lo eth0
iface lo inet loopback

allow-hotplug eth0
iface eth0 inet dhcp
EOF
	# # temporarily remove upstart crap...
	# if [ -e ${mnt}/sbin/initctl ]; then
	#     mv ${mnt}/sbin/initctl ${mnt}/sbin/initctl.old
	#     ln -s /bin/true ${mnt}/sbin/initctl
	# fi

	# chroot ${mnt} apt-get install -y --force-yes libnss-mdns avahi-daemon

	# if [ -e ${mnt}/sbin/initctl.old ]; then
	#     rm -f ${mnt}/sbin/initctl
	#     mv ${mnt}/sbin/initctl.old ${mnt}/sbin/initctl
	# fi
    cat > ${mnt}/etc/hosts <<EOF
127.0.0.1       localhost
127.0.1.1       ${name}

# The following lines are desirable for IPv6 capable hosts
::1     ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
EOF
    cat > ${mnt}/etc/resolv.conf <<EOF
nameserver 127.0.0.1
EOF
    ;;

    *)
	echo "Skipping network creation.  Unknown distrelease"
	;;
esac

if [ -e ${mnt}/etc/udev/rules.d/70-persistent-net.rules ]; then
    rm ${mnt}/etc/udev/rules.d/70-persistent-net.rules
fi



