#!/bin/bash

# $1 - name
# $2 - distrelease
# $3 - mountpoint

name=${1}
distrelease=${2}
mnt=${3}

dist=${distrelease%%-*}
release=${distrelease##*-}

case ${dist} in
    ubuntu)
        mirror=${UBUNTU_MIRROR:-http://mirror.rackspace.com}
        cat > ${mnt}/etc/apt/sources.list.d/local.list <<EOF
deb ${mirror}/${dist} ${release} main universe multiverse
deb ${mirror}/${dist} ${release}-updates main universe multiverse
EOF

        chroot ${mnt} apt-get update
        ;;
    *)
        echo "Can't do that, boss"
        ;;
esac

exit 0
