#!/bin/bash

# $1 - name
# $2 - distrelease
# $3 - mountpoint

name=${1}
distrelease=${2}
mnt=${3}

for i in ${EXTRA_NICS}; do
    sudo virsh attach-interface $name bridge $i --persistent --model virtio
done
