#!/bin/bash

function make_cow_from_sized_base() {
    local distrelease=${1}
    local size=${2}
    local name=${3}

    echo "Creating QCOW2 cow image"
    qemu-img create -f qcow2 -o backing_file=${BASE_DIR}/base/${distrelease}-${size}.qcow2 "${BASE_DIR}/instances/${name}/${name}.qcow2"
}

function make_raw_device() {
    local distrelease=${1}
    local size=${2}
    local name=${3}

    tmpfile=$(mktemp)
    dd if=/dev/zero of=${tmpfile} bs=1 count=0 seek=${size}G
    _RETVAL=${tmpfile}
}

function destroy_raw_device() {
    local devicename=${1}
    rm -f ${devicename}
}

function finalize_sized_base() {
    local devicename=${1}
    local destname=${2}

    qemu-img convert -f raw -O qcow2 -o preallocation=metadata ${devicename} ${destname}
    rm -f ${devicename}
}

function have_sized_base {
    local distrelease=${1}
    local size=${2}

    if [ -e ${BASE_DIR}/base/${distrelease}-${size}.qcow2 ]; then
	return 0
    fi

    return 1
}

