#!/bin/bash

# $1 - ip (assumes passwordless ssh)
# $2 - distrelease
# $3 - hints

# This script works without a genlocalrc helper, but if you wish to
# upload a special localrc, you will need to define CONTRIB_DIR in
# your .fakecloudrc and put a script called genlocalrc.sh that defines
# a genlocalrc function.  The genlocalrc function takes a filename and
# outputs a localrc file into said filename.

ip=${1}
distrelease=${2}
hints=${3}

dist=${distrelease%%-*}
release=${distrelease##*-}

[ -e /home/${SUDO_USER}/.ssh/id_dsa ] && IDENTITY_FILE=/home/${SUDO_USER}/.ssh/id_dsa
[ -e /home/${SUDO_USER}/.ssh/id_rsa ] && IDENTITY_FILE=/home/${SUDO_USER}/.ssh/id_rsa

SSHOPS="-o UserKnownhostsFile=/dev/null -o StrictHostKeyChecking=no"
if [ "${IDENTITY_FILE-}" != "" ]; then
    SSHOPS+=" -i${IDENTITY_FILE}"
fi

case ${distrelease} in
    ubuntu*)
	ssh ${SSHOPS} root@${ip} DEBIAN_FRONTEND=noninteractive apt-get -y install git
	ssh ${SSHOPS} root@${ip} 'cd /opt && git clone https://github.com/openstack-dev/devstack'
        # https://github.com/chalupaul/devstackhelper/blob/master/genlocalrc.sh
        echo $CONTRIB_DIR ahhaah
        [ -f $CONTRIB_DIR/genlocalrc.sh ] && source $CONTRIB_DIR/genlocalrc.sh
        if declare -f genlocalrc &> /dev/null; then
            localrc=$(tempfile)
            genlocalrc $localrc
            scp ${SSHOPS} $localrc root@${ip}:/opt/devstack/localrc
            rm $localrc
        fi
	;;

    *)
	echo "Can't do, boss."
	;;
esac

