#!/bin/bash

function handle_request() {
    mkdir -p ${TOKEN_DIR}

    if [[ ${headers[x-auth-user]:-} == "" ]] || [[ ${headers[x-auth-key]:-} = "" ]]; then
	response "400 Bad Request" "text/plain" "Expecting x-auth-user and x-auth-key"
    fi



    response_headers[x-auth-token]="howdy"
    response "204 No Content" "text/plain"
    exit 0
}
